---
- name: Create mac_identifier service directory
  become: true
  file:
    path: "{{ mac_identifier_deploy_dir }}"
    state: directory
    mode: 0755
    owner: "{{ default_user }}"
    group: "{{ default_user }}"

- name: Render docker-compose file
  become: true
  template:
    src: docker-compose.yml
    dest: "{{ mac_identifier_deploy_dir }}/docker-compose.yml"
    mode: 0644
    owner: "{{ default_user }}"
    group: "{{ default_user }}"

