- name: Stop mac_identifier
  command:
    argv:
      - "/usr/bin/docker"
      - "compose"
      - "down"
    chdir: "{{ mac_identifier_deploy_dir }}"
  become: true
  ignore_errors: true

- name: Start mac_identifier
  command:
    argv:
      - "/usr/bin/docker"
      - "compose"
      - "up"
      - "-d"
      - "--force-recreate"
    chdir: "{{ mac_identifier_deploy_dir }}"
  become: true
